# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196e2f18a3a257bab452027c929fcd8e9dc71b622bee789262d5a955d2ecae9b000f61cb48cfaf06f4e441e721399e0f1478983ebd7a5319cd48f17701f76c16

test:
  secret_key_base: c13548a77494067864ba203607b2d1bb082afe053f50c118b0ad492363f6f18930f42c46f7e3c757d7d81f1e7343e900e6068b2be234dff5d3c7e08893926813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
